src/ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.home_view, name="home"),
    path("products/", include("products.urls")),
    path("purchase/", include("purchase.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("", views.product_list_view, name="product_list"),
    path("create/", views.product_create_view, name="create"),
    path("<slug:product_slug>/", views.product_detail_view, name="product_detail"),
    path("<slug:product_slug>/download/<int:pk>",
         views.product_attachment_download_view, name="attachment_download"),

    path("<slug:product_slug>/manage/",
         views.product_manage_detail_view, name="manage"),
]

src/purchase/urls.py
from django.urls import path
from . import views

app_name = "purchase"

urlpatterns = [
    path("start/", views.purchase_start_view, name="start"),
    path("stop/", views.purchase_stop_view, name="stop"),
    path("success/", views.purchase_success_view, name="success"),
]

src/purchase/models.py
from django.db import models
from django.conf import settings
from products.models import Product

# Create your models here.


class Purchase(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             default=1,
                             on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    completed = models.BooleanField(default=False)
    product_price = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

src/purchase/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from products.models import Product
from purchase.models import Purchase

# Create your views here.


def purchase_start_view(request):
    if not request.method == "POST":
        return HttpResponseBadRequest()

    if not request.user.is_authenticated:
        return HttpResponseBadRequest()

    product_slug = request.POST.get("handle")
    product = Product.objects.get(product_slug=product_slug)

    obj = Purchase.objects.create(user=request.user, product=product)
    print("this is session", request.session)

    request.session["purchase_id"] = obj.id

    # for i in request.session.items():
    #     print("this is session:", i)
    print("after buy this is session", request.session)
    print("this is handle::", product_slug)
    print("this is product::", product)
    # print("this is purchase id::", obj.id)

    return HttpResponseRedirect("/purchase/stop/")


def purchase_stop_view(request):

    return HttpResponse(f"Stopped")


def purchase_success_view(request):
    purchase_id = request.session.get("purchase_id")
    name = None
    if purchase_id:
        obj = Purchase.objects.get(id=purchase_id)
        name = obj.product
        obj.completed = True
        obj.save()

    return HttpResponse(f"Thanks for buying {name} --- {purchase_id}")

src/purchase/templates/purchase/buy_btn_form.html
{% if product %}
  <form method="post" action="{% url 'purchase:start' %}" class="my-2" >
    {% csrf_token %}

    <input type="hidden" value="{{ product.product_slug }}" name="handle" />

    <div class="flex items-baseline text-gray-900 dark:text-white my-4">
      <span class="text-3xl font-semibold">$</span>
      <span class="text-5xl font-extrabold tracking-tight">{{ product.product_price }}</span>
    </div>

    {% if request.user.is_authenticated %}
      <button type="submit" class="focus:outline-none text-white text-lg md:text-xl bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900">Buy Now</button>
    {% else %}
      <a href="#" class="focus:outline-none text-white text-lg md:text-xl bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900 my-2">Login To Purchase</a>
    {% endif %}
  </form>
{% endif %}