src/ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.home_view, name="home"),
    path("products/", include("products.urls")),
    path("purchase/", include("purchase.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("", views.product_list_view, name="product_list"),
    path("create/", views.product_create_view, name="create"),
    path("<slug:product_slug>/", views.product_detail_view, name="product_detail"),
    path("<slug:product_slug>/download/<int:pk>",
         views.product_attachment_download_view, name="attachment_download"),

    path("<slug:product_slug>/manage/",
         views.product_manage_detail_view, name="manage"),
]

src/templates/base/footer.html
<footer class="bg-white rounded-lg shadow-md dark:bg-gray-800 m-4">
  <div class="w-full mx-auto container p-4 md:p-6 md:flex md:items-center md:justify-between">
    <div class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
      &copy; <span id="year"></span> <a href="/" class="hover:underline"> Micro eCommerce</a>.  All Rights Reserved.
    </div>
    <ul class="flex flex-wrap items-center mt-3 text-sm sm:mt-0 text-gray-400 dark:text-gray-500">
      <li>
        <a href="#" class="mr-4 hover:underline md:mr-6">About</a>
      </li>
      <li>
        <a href="#" class="mr-4 hover:underline md:mr-6">Privacy Policy</a>
      </li>
      <li>
        <a href="#" class="mr-4 hover:underline md:mr-6">Licensing</a>
      </li>
      <li>
        <a href="#" class="mr-4 hover:underline md:mr-6">Contact</a>
      </li>
    </ul>
  </div>
</footer>

src/templates/base/navbar.html
<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
  <div class="container flex flex-wrap items-center justify-between mx-auto">
    <a href="/" class="flex items-center"><span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Micro eCommerce</span></a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <a href="#" class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" aria-current="page">Home</a>
        </li>

        <li>
          <a href="{% url 'products:product_list' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Products</a>
        </li>
      </ul>
    </div>
  </div>
</nav>